#!/bin/bash
if [ "$1" = "" ]
then
  echo "usage: $0 {main|chill|status|labsocket|alarm|screen} {on|off}"
  echo "usage: $0 {projector} {on|hdmi1|hdmi2|dvi|vga1|off}"
  echo "usage; $0 {receiver} {on|off|hdmi|jack1|jack2|optical|vol-|vol+}"
#  echo "usage: $0 {maindoor} {open}"
  exit 1
fi
function dolight() {
  if [ "$2" = "on" ]
  then
    setvalue=1
  else
    setvalue=0
  fi
  case "$1" in
    all) dolight "main" $2
         dolight "status" $2
         dolight "labsocket" $2
         dolight "alarm" $2
         ;; 
    main)      sudo /root/pidor/rcswitch-pi/send 2 1A 1 "$setvalue"
         ;; 
    chill)     sudo /root/pidor/rcswitch-pi/send 2 1A 2 "$setvalue"
         ;; 
    status)    sudo /root/pidor/rcswitch-pi/send 2 2A 1 "$setvalue"
         ;; 
    labsocket) sudo /root/pidor/rcswitch-pi/send 2 15A 6 "$setvalue"
         ;; 
    alarm)     sudo /root/pidor/rcswitch-pi/send 2 15A 1 "$setvalue"
         ;; 
    screen)    sudo /root/pidor/scripts/beamercontrol.sh screen "$2"
         ;;
    projector) sudo /root/pidor/scripts/beamercontrol.sh beamer "$2"
         ;;
    receiver)  sudo /root/pidor/scripts/beamercontrol.sh receiver "$2"
         ;;
#    maindoor)  sudo /root/pidor/scripts/opendoor.sh
#         ;;
  esac
  #                       type (2=10bit)
  #                       | house 1-16 (the dial thingie)
  #                       | |group A-P (the dial thingie)
  #                       | || unit (1-16) (the button, usually 1-4)
  #                       | || | on/off
  #                       | || | |
  #/usr/local/bin/433send 2 1A 1 1 #on
  #/usr/local/bin/433send 2 1A 1 0 #off
}

logger -t $(basename $0) "$$ $1 $2"
dolight "$1" "$2"
